apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-inntektsmelding
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  envFrom:
    - secret: flex-inntektsmelding-serviceuser
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: inntektsmeldingdb
            diskAutoresize: true
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
